"""
Сервис для создания и управления персональными ассистентами.
Генерирует zip-бандл агента с шаблонным кодом.
"""
import base64
import hashlib
import io
import json
import zipfile

from cryptography.fernet import Fernet

# ── Персоны (имена пчёл/ос) ───────────────────────────────────────────────────
ASSISTANT_PERSONAS = [
    ("Maya", "🐝"), ("Buzz", "🐝"), ("Vespa", "🪲"), ("Hornet", "🟡"),
    ("Bomba", "🐝"), ("Sting", "🐝"), ("Amber", "🐝"), ("Stripe", "🐝"),
    ("Apis", "🐝"), ("Osmia", "🐝"), ("Polly", "🐝"), ("Cleo", "🐝"),
    ("Vespera", "🐝"), ("Reina", "🐝"), ("Furia", "🐝"), ("Nova", "🐝"),
    ("Zara", "🐝"), ("Dora", "🐝"), ("Kira", "🐝"), ("Sera", "🐝"),
    ("Bex", "🐝"), ("Wren", "🐝"), ("Hex", "🐝"), ("Nyx", "🐝"),
]

# ── Шаблон кода агента ────────────────────────────────────────────────────────
_AGENT_TEMPLATE = '''\
# Personal assistant agent — auto-generated by HiveMind
import json, os, re, urllib.request, urllib.error
from agentshub import get_input, discover_agents, call_agent


def _llm(provider, key, msgs, system):
    if provider == "gemini":
        url = (
            "https://generativelanguage.googleapis.com/v1beta/models/"
            f"gemini-2.0-flash:generateContent?key={key}"
        )
        contents = []
        for m in msgs:
            role = "model" if m["role"] in ("assistant", "model") else "user"
            contents.append({"role": role, "parts": [{"text": m["content"]}]})
        body = {
            "system_instruction": {"parts": [{"text": system}]},
            "contents": contents,
            "generationConfig": {"maxOutputTokens": 1500},
        }
        req = urllib.request.Request(
            url, json.dumps(body).encode(), {"Content-Type": "application/json"}
        )
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.loads(r.read())
        return data["candidates"][0]["content"]["parts"][0]["text"]

    elif provider == "openai":
        body = {
            "model": "gpt-4o-mini",
            "max_tokens": 1500,
            "messages": [{"role": "system", "content": system}] + msgs,
        }
        req = urllib.request.Request(
            "https://api.openai.com/v1/chat/completions",
            json.dumps(body).encode(),
            {"Content-Type": "application/json", "Authorization": f"Bearer {key}"},
        )
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.loads(r.read())
        return data["choices"][0]["message"]["content"]

    elif provider == "anthropic":
        body = {
            "model": "claude-haiku-4-5-20251001",
            "max_tokens": 1500,
            "system": system,
            "messages": msgs,
        }
        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            json.dumps(body).encode(),
            {
                "Content-Type": "application/json",
                "x-api-key": key,
                "anthropic-version": "2023-06-01",
            },
        )
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.loads(r.read())
        return data["content"][0]["text"]

    raise ValueError(f"Unknown provider: {provider}")


# ── Main ─────────────────────────────────────────────────────────────────────
inp = get_input()
message = inp.get("message", inp.get("text", ""))
history = inp.get("_conversation_history", [])
provider = os.environ.get("ASSISTANT_PROVIDER", "gemini")
api_key = os.environ.get("ASSISTANT_API_KEY", "")

if not message:
    print(json.dumps({"error": "No message provided"}))
    raise SystemExit(1)

if not api_key:
    print(json.dumps({"error": "No API key configured. Please set up your assistant."}))
    raise SystemExit(1)

# Discover hub agents
try:
    hub_agents = discover_agents(limit=30)
    if hub_agents:
        agents_ctx = "\\n".join([
            f"- {a[\'slug\']}: {a.get(\'description\') or \'\'}"
            + (f" [caps: {', '.join(a[\'capabilities\'])}]" if a.get("capabilities") else "")
            for a in hub_agents
        ])
    else:
        agents_ctx = "(No agents available in hub yet)"
except Exception as e:
    agents_ctx = f"(Hub unavailable: {e})"
    hub_agents = []

system_prompt = (
    "You are a smart personal AI assistant that can interact with a hub of specialized AI agents.\\n\\n"
    f"Available hub agents:\\n{agents_ctx}\\n\\n"
    "To call a hub agent, use this exact format:\\n"
    "<tool_call>\\n{\\"agent\\": \\"owner/agent-name\\", \\"input\\": {\\"key\\": \\"value\\"}}\\n</tool_call>\\n\\n"
    "If no agent is needed, respond directly. Use the same language as the user. Be concise."
)

# Build message history
msgs = []
for h in (history or [])[-10:]:
    role = h.get("role", "user")
    if role not in ("user", "assistant", "model"):
        role = "user"
    msgs.append({
        "role": "user" if role == "user" else "assistant",
        "content": str(h.get("content", "")),
    })
msgs.append({"role": "user", "content": message})

# First LLM call
try:
    response = _llm(provider, api_key, msgs, system_prompt)
except urllib.error.HTTPError as e:
    err_body = e.read().decode()[:300]
    print(json.dumps({"error": f"LLM API error {e.code}: {err_body}"}))
    raise SystemExit(1)
except Exception as e:
    print(json.dumps({"error": f"LLM call failed: {e}"}))
    raise SystemExit(1)

# Check for tool call
tool_match = re.search(r\'<tool_call>\\s*(\\{.*?\\})\\s*</tool_call>\', response, re.DOTALL)
agent_called = None
agent_result = None

if tool_match:
    try:
        tool = json.loads(tool_match.group(1))
        agent_slug = tool["agent"]
        agent_input = tool.get("input", {})

        agent_result = call_agent(agent_slug, agent_input)
        agent_called = agent_slug

        msgs.append({"role": "assistant", "content": response})
        msgs.append({
            "role": "user",
            "content": (
                f"Agent \'{agent_slug}\' responded:\\n"
                f"{json.dumps(agent_result, ensure_ascii=False, indent=2)}\\n\\n"
                "Please present this to the user in a clear and helpful way."
            ),
        })
        response = _llm(provider, api_key, msgs, system_prompt)
        response = re.sub(r\'<tool_call>.*?</tool_call>\', "", response, flags=re.DOTALL).strip()
    except Exception as e:
        response = re.sub(r\'<tool_call>.*?</tool_call>\', "", response, flags=re.DOTALL).strip()
        response += f"\\n\\n_(Tried to call an agent but got an error: {e})_"

out = {"response": response}
if agent_called:
    out["agent_called"] = agent_called
if agent_result is not None:
    out["agent_result"] = agent_result

print(json.dumps(out, ensure_ascii=False))
'''


def _fernet(secret: str) -> Fernet:
    key = hashlib.sha256(secret.encode()).digest()
    return Fernet(base64.urlsafe_b64encode(key))


def encrypt_key(api_key: str, secret: str) -> str:
    return _fernet(secret).encrypt(api_key.encode()).decode()


def decrypt_key(encrypted: str, secret: str) -> str:
    return _fernet(secret).decrypt(encrypted.encode()).decode()


def build_assistant_bundle(name: str, emoji: str) -> bytes:
    """Создаёт zip-архив с кодом персонального ассистента."""
    manifest = {
        "name": f"{name.lower()}-assistant",
        "version": "1.0.0",
        "runtime": "python3.11",
        "entrypoint": "main.py",
        "description": f"Personal assistant {emoji} {name} — your AI concierge in the hub",
        "uses_agents": ["*"],
        "capabilities": ["assistant", "chat", "orchestration"],
        "timeout_seconds": 90,
        "price_per_call": 0,
    }

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("main.py", _AGENT_TEMPLATE)
        zf.writestr("manifest.json", json.dumps(manifest, indent=2))
    buf.seek(0)
    return buf.read()
