[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_escrow = "7dnUyWpJ2JNbCWNRjy5paJXq8bYD5QPpwe6tf1ZAGGaY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/platform-keypair.json"

[scripts]
test = "NODE_OPTIONS='--import tsx' yarn run mocha -t 1000000 'tests/**/*.ts' --exit"
