[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_escrow = "2qP9GpKCspihqmSggbmu5gg5q5TdDiSGT2JcUhBjUC4G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS='--import tsx' yarn run mocha -t 1000000 'tests/**/*.ts' --exit"
